# if you don’t have the file locally, create it exactly as below:
cat <<'YAML' > svc-webapp-apps.yaml
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: apps
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      targetPort: http
YAML

kubectl apply -f svc-webapp-apps.yaml
kubectl -n apps get svc webapp
