apiVersion: v1
kind: Service
metadata:
  name: mc-app-service
  labels:
    app: mc-app
spec:
  type: LoadBalancer
  selector:
    app: mc-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
